# 是否反汇编（单步模式中打印流水线时会使用）
disassemble: false
# riscv的objdump的路径（若不反汇编则可以忽略该参数）
objdump: riscv64-unknown-elf-objdump
# 是否进行数据前递
data_forwarding: true
# 转移预测策略
branch_predictor: branch_history_table
# 栈大小，单位是KB
stack_size: 1024
# 配置ALU不同运算所需周期数
alu_cycles:
  add_sub: 1
  mul: 3
  div_rem: 30
  bit_op: 1
  slt: 1
# 配置不同系统调用所需周期数
ecall_cycles:
  cputchar: 2000
  sbrk: 1000
  readint: 10000
  time: 1000
# 访问主存所需周期数
memory_cycles: 100
# 配置Cache层次结构
cache:
  -
    name: single_level
    data_entry: true
    cache_for: memory
    hit_cycles: 1
    # write_back: true
    # write_allocate: true
    # size: 32
    # associativity: 8
    # cache_line_bytes: 32
