# 访问主存所需周期数
memory_cycles: 13
# 配置Cache层次结构
cache:
  -
    name: L1_cache
    data_entry: true
    instruction_entry: true
    size: 32
    associativity: 8
    cache_line_bytes: 64
    write_back: true
    write_allocate: true
    hit_cycles: 1
    cache_for: L2_cache
  -
    name: L2_cache
    size: 256
    associativity: 8
    cache_line_bytes: 64
    write_back: true
    write_allocate: true
    hit_cycles: 2
    cache_for: L3_cache
  -
    name: L3_cache
    size: 8192
    associativity: 8
    cache_line_bytes: 64
    write_back: true
    write_allocate: true
    hit_cycles: 4
    cache_for: memory
